### ISSUE TITLE
User deactivation doesn't work

### ISSUE THREAD

**Issue by prattsj** [LearnersGuild/echo#1022]
```
2017-07-14T13:38:59.316393+00:00 app[web.2]: Error while removing user from GitHub organizations. APIError: API Error 404 (Not Found) trying to invoke API (url = 'https://api.github.com/orgs/LearnersGuild/members/testuser')
2017-07-14T13:38:59.316402+00:00 app[web.2]:     at Object.construct (/app/node_modules/core-js/modules/es6.reflect.construct.js:31:24)
2017-07-14T13:38:59.316404+00:00 app[web.2]:     at APIError.ExtendableBuiltin (/app/src/server/util/api.js:29:28)
2017-07-14T13:38:59.316405+00:00 app[web.2]:     at new APIError (/app/src/server/util/api.js:5:53)
2017-07-14T13:38:59.316405+00:00 app[web.2]:     at /app/src/server/util/api.js:25:17
2017-07-14T13:38:59.316406+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.316407+00:00 app[web.2]:     at Promise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
2017-07-14T13:38:59.316407+00:00 app[web.2]:     at Promise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.316408+00:00 app[web.2]:     at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:471:26)
2017-07-14T13:38:59.316409+00:00 app[web.2]:     at run (/app/node_modules/core-js/modules/es6.promise.js:87:22)
2017-07-14T13:38:59.316409+00:00 app[web.2]:     at /app/node_modules/core-js/modules/es6.promise.js:100:28
2017-07-14T13:38:59.316410+00:00 app[web.2]:     at flush (/app/node_modules/core-js/modules/_microtask.js:18:9)
2017-07-14T13:38:59.316411+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.316411+00:00 app[web.2]:     at nextTickCallbackWith0Args (node.js:453:9)
2017-07-14T13:38:59.316412+00:00 app[web.2]:     at process._tickDomainCallback [as _tickCallback] (node.js:423:13)
2017-07-14T13:38:59.592248+00:00 app[web.2]: Error while removing user from Heroku apps. APIError: API Error 403 (Forbidden) trying to invoke API (url = 'https://api.heroku.com/apps/undefined/collaborators/test.user@gmail.com')
2017-07-14T13:38:59.592252+00:00 app[web.2]:     at Object.construct (/app/node_modules/core-js/modules/es6.reflect.construct.js:31:24)
2017-07-14T13:38:59.592253+00:00 app[web.2]:     at APIError.ExtendableBuiltin (/app/src/server/util/api.js:29:28)
2017-07-14T13:38:59.592253+00:00 app[web.2]:     at new APIError (/app/src/server/util/api.js:5:53)
2017-07-14T13:38:59.592254+00:00 app[web.2]:     at /app/src/server/util/api.js:25:17
2017-07-14T13:38:59.592254+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.592255+00:00 app[web.2]:     at Promise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
2017-07-14T13:38:59.592256+00:00 app[web.2]:     at Promise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.592257+00:00 app[web.2]:     at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:471:26)
2017-07-14T13:38:59.592257+00:00 app[web.2]:     at run (/app/node_modules/core-js/modules/es6.promise.js:87:22)
2017-07-14T13:38:59.592258+00:00 app[web.2]:     at /app/node_modules/core-js/modules/es6.promise.js:100:28
2017-07-14T13:38:59.592258+00:00 app[web.2]:     at flush (/app/node_modules/core-js/modules/_microtask.js:18:9)
2017-07-14T13:38:59.592259+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.592259+00:00 app[web.2]:     at nextTickCallbackWith0Args (node.js:453:9)
2017-07-14T13:38:59.592260+00:00 app[web.2]:     at process._tickDomainCallback [as _tickCallback] (node.js:423:13)
2017-07-14T13:38:59.647893+00:00 app[web.2]: Error while deactivating user in the chat system. APIError: API Error 400 (Bad Request) trying to invoke API (url = 'https://api.slack.com/scim/v1/Users/75dbe257-a701-4725-ba74-4341376f540d')
2017-07-14T13:38:59.647896+00:00 app[web.2]:     at Object.construct (/app/node_modules/core-js/modules/es6.reflect.construct.js:31:24)
2017-07-14T13:38:59.647897+00:00 app[web.2]:     at APIError.ExtendableBuiltin (/app/src/server/util/api.js:29:28)
2017-07-14T13:38:59.647898+00:00 app[web.2]:     at new APIError (/app/src/server/util/api.js:5:53)
2017-07-14T13:38:59.647899+00:00 app[web.2]:     at /app/src/server/util/api.js:25:17
2017-07-14T13:38:59.647900+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.647900+00:00 app[web.2]:     at Promise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:295:65)
2017-07-14T13:38:59.647901+00:00 app[web.2]:     at Promise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.647902+00:00 app[web.2]:     at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:471:26)
2017-07-14T13:38:59.647902+00:00 app[web.2]:     at run (/app/node_modules/core-js/modules/es6.promise.js:87:22)
2017-07-14T13:38:59.647903+00:00 app[web.2]:     at /app/node_modules/core-js/modules/es6.promise.js:100:28
2017-07-14T13:38:59.647903+00:00 app[web.2]:     at flush (/app/node_modules/core-js/modules/_microtask.js:18:9)
2017-07-14T13:38:59.647904+00:00 app[web.2]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2017-07-14T13:38:59.647904+00:00 app[web.2]:     at nextTickCallbackWith0Args (node.js:453:9)
2017-07-14T13:38:59.647905+00:00 app[web.2]:     at process._tickDomainCallback [as _tickCallback] (node.js:423:13)
2017-07-14T13:38:59.742373+00:00 app[web.2]: GraphQL ERROR: { data: { deactivateUser: null },
2017-07-14T13:38:59.742376+00:00 app[web.2]:   errors: [ { message: 'currentUser.roles.include is not a function' } ] }
2017-07-14T13:38:59.749694+00:00 app[web.2]: TypeError:
2017-07-14T13:38:59.749696+00:00 app[web.2]:         TypeError: Cannot read property 'data' of undefined
```

**Comment by prattsj** [comment]
Most of these failures were due to this user having already been (presumably manually) removed from linked systems (GitHub, Heroku).

There is a bug in idm, however. Moving this issue.

**Comment by prattsj** [comment]
Issue moved to [LearnersGuild/idm #179](https://github.com/LearnersGuild/idm/issues/179) via [**ZenHub**](https://www.zenhub.com/)
